# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='alarmTpMax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='alarmTpMin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
